import Head from 'next/head';
import Script from 'next/script';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import axios from 'axios';
import Axios from '@/helper/axios.helper'
import dynamic from 'next/dynamic'
import Layout from '@/components/Layout';
import { faCoffee, faSun, faMoon } from '@fortawesome/free-solid-svg-icons'
import { NextResponse } from 'next/server'
import { pages } from '@/utils/contanst'
// import '@/styles/globals.css'
//import { BsSun, BsFillMoonStarsFill, BsFillBellFill,BsFillGridFill } from "react-icons/bs"

export async function getServerSideProps({ req, res }) {
    const token = req.cookies["vechaitoken"];
    const { data } = await Axios({
        url: "/api/user/getbytoken",
        method: "GET",
        headers: { authorization: token },
    })
    if (!data) NextResponse.redirect(new URL('/login', request.url))

    return {
        props: {
            userData: data[0]
        },
    };
}

export default function Dashboard({ userData }) {
    const { fullname, name, email, accessApp } = userData;
    const [layoutPages, setLayoutPages] = useState([])

    const Map = dynamic(() => import("@/components/Map"), {
        ssr: false,
        loading: () => <p>Loading...</p>,
    });
    useEffect(() => {
        const accessAppList = accessApp.split(', ')
        if (accessAppList && Array.isArray(accessAppList)) {
            let foundePages = []
            pages.forEach((page, index) => {
                if(accessAppList.includes(page.key)) {
                    foundePages.push(page)
                }
            })
            setLayoutPages(foundePages)
        }
    }, [])

    const handelLogout = () => {
        setCookie('vechaitoken', '')
        window.location.reload()

    }



    return <>
        <Head>
            <title>Trang chủ</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/assets/img/logo1.PNG" />
        </Head>
        <main>
            {/* <!-- Dashboard --> */}

            {/* <!-- ======End Topbar======= --> */}
            <Layout pages={layoutPages} user={{ fullname, email }}>
                <div className="section flex flex-sb">
                    {/* <!-- Section Left --> */}
                    <div className="section-left">
                        {/* <!-- ======Banner======= --> */}
                        <div className="banner flex flex-sb">
                            <div className="text">
                                <h2>
                                    Dicover and sell <br />
                                    your own NFTs
                                </h2>

                                <a href="#" className="btn">
                                    Discover Now
                                </a>
                            </div>

                            <img
                                src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/banner.svg"
                                alt=""
                            />
                        </div>

                        <div className="nfts">
                            {/* <Map></Map> */}
                            <div className="trending heading flex flex-sb">
                                <h2>Trending NFTs</h2>
                                <p>See all</p>
                            </div>
                            <Map />
                            {/* <!-- ======Categories======= --> */}

                            <div className="categories flex flex-sb">
                                <div className="category flex">
                                    <div className="icon">🔥</div>
                                    <p>Trending</p>
                                </div>

                                <div className="category flex">
                                    <div className="icon">🎨</div>
                                    <p>Art</p>
                                </div>

                                <div className="category flex">
                                    <div className="icon">🕹️</div>
                                    <p>Game</p>
                                </div>

                                <div className="category flex">
                                    <div className="icon">👗</div>
                                    <p>Fashion</p>
                                </div>

                                <div className="category flex">
                                    <div className="icon">🎵</div>
                                    <p>Music</p>
                                </div>
                            </div>

                            {/* <!-- =====Browse NFT===== --> */}
                            <div className="browse">
                                <div className="nft">
                                    <img
                                        src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-1.jpg"
                                        alt=""
                                    />
                                    <div className="title">Weary Artwork</div>
                                    <div className="details flex flex-sb">
                                        <div className="author flex">
                                            <img
                                                src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                                alt=""
                                            />
                                            <p>Hassnain Haider</p>
                                        </div>
                                        <div className="price">4.5 ETH</div>
                                    </div>
                                </div>

                                <div className="nft">
                                    <img
                                        src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-2.jpg"
                                        alt=""
                                    />
                                    <div className="title">Spectrum of Color</div>
                                    <div className="details flex flex-sb">
                                        <div className="author flex">
                                            <img
                                                src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                                alt=""
                                            />
                                            <p>Hassnain Haider</p>
                                        </div>
                                        <div className="price">4 ETH</div>
                                    </div>
                                </div>

                                <div className="nft">
                                    <img
                                        src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-3.jpg"
                                        alt=""
                                    />
                                    <div className="title">Vivid Artwork</div>
                                    <div className="details flex flex-sb">
                                        <div className="author flex">
                                            <img
                                                src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                                alt=""
                                            />
                                            <p>Hassnain Haider</p>
                                        </div>
                                        <div className="price">3.5 ETH</div>
                                    </div>
                                </div>

                                <div className="nft">
                                    <img
                                        src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-4.jpg"
                                        alt=""
                                    />
                                    <div className="title">Nature's Love</div>
                                    <div className="details flex flex-sb">
                                        <div className="author flex">
                                            <img
                                                src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                                alt=""
                                            />
                                            <p>Hassnain Haider</p>
                                        </div>
                                        <div className="price">5 ETH</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* <!-- Section Right --> */}
                    <div className="section-right">
                        <div className="graph flex-c">
                            <p>Balance</p>
                            <h2>93,565.00</h2>

                            <img
                                src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/graph.svg"
                                alt=""
                            />
                        </div>

                        <div className="top-creators">
                            <div className="heading flex flex-sb">
                                <h2>Top Creators</h2>
                                <p>See all</p>
                            </div>

                            <div className="creator flex flex-sb">
                                <div className="follow-creator flex">
                                    <img
                                        src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                        alt=""
                                    />
                                    <div className="creator-details">
                                        <h3>Hassnain Haider</h3>
                                        <p>@hassnain</p>
                                    </div>
                                </div>

                                <a href="#" className="btn following">
                                    Following
                                </a>
                            </div>

                            <div className="creator flex flex-sb">
                                <div className="follow-creator flex">
                                    <img
                                        src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                        alt=""
                                    />
                                    <div className="creator-details">
                                        <h3>Hassnain Haider</h3>
                                        <p>@hassnain</p>
                                    </div>
                                </div>

                                <a href="#" className="btn follow following">
                                    Follow
                                </a>
                            </div>

                            <div className="creator flex flex-sb">
                                <div className="follow-creator flex">
                                    <img
                                        src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                        alt=""
                                    />
                                    <div className="creator-details">
                                        <h3>Hassnain Haider</h3>
                                        <p>@hassnain</p>
                                    </div>
                                </div>

                                <a href="#" className="btn follow following">
                                    Follow
                                </a>
                            </div>

                            <div className="creator flex flex-sb">
                                <div className="follow-creator flex">
                                    <img
                                        src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                        alt=""
                                    />
                                    <div className="creator-details">
                                        <h3>Hassnain Haider</h3>
                                        <p>@hassnain</p>
                                    </div>
                                </div>

                                <a href="#" className="btn follow following">
                                    Follow
                                </a>
                            </div>

                            <div className="creator flex flex-sb">
                                <div className="follow-creator flex">
                                    <img
                                        src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                        alt=""
                                    />
                                    <div className="creator-details">
                                        <h3>Hassnain Haider</h3>
                                        <p>@hassnain</p>
                                    </div>
                                </div>

                                <a href="#" className="btn follow following">
                                    Follow
                                </a>
                            </div>

                            <div className="creator flex flex-sb">
                                <div className="follow-creator flex">
                                    <img
                                        src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                        alt=""
                                    />
                                    <div className="creator-details">
                                        <h3>Hassnain Haider</h3>
                                        <p>@hassnain</p>
                                    </div>
                                </div>

                                <a href="#" className="btn follow following">
                                    Follow
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </Layout>
            {/* <!-- ======Section======= --> */}

            {/* <!-- ======End Section======= --> */}

            {/* <!-- End Dashboard --> */}
        </main>
        <Script src="/js/dashboard.js"></Script>
    </>

} 