import Head from 'next/head'
import Image from 'next/image'
import { Homemade_Apple, Inter } from 'next/font/google'
import React, { useState } from 'react'
import styles from '@/styles/Home.module.scss'
import Scripts from 'next/script'
import Axios from '@/helper/axios.helper'
import Footer from '@/components/Footer'
import Narvbarhome from '@/components/Navbarhome'
import Link from 'next/link'
import {
  Collapse,
  Navbar,
  Container,
  Row,
  Col,
  Card,
  CardImg,
  CardBody,
  CardTitle,
  CardSubtitle,
  CardText,
  Button,
  NavbarToggler,
  NavbarBrand,
  Nav,
  NavItem,
  NavLink,
  UncontrolledDropdown,
  DropdownToggle,
  DropdownMenu,
  DropdownItem,
  NavbarText,
  CardGroup
} from 'reactstrap';
import {
  Carousel,
  CarouselItem,
  CarouselControl,
  CarouselIndicators,
  CarouselCaption,

} from 'reactstrap';

import "bootstrap/dist/css/bootstrap.min.css";
function Banner(args) {
  const [activeIndex, setActiveIndex] = useState(0);
  const [animating, setAnimating] = useState(false);
  const next = () => {
    if (animating) return;
    const nextIndex = activeIndex === items.length - 1 ? 0 : activeIndex + 1;
    setActiveIndex(nextIndex);
  };
  const previous = () => {
    if (animating) return;
    const nextIndex = activeIndex === 0 ? items.length - 1 : activeIndex - 1;
    setActiveIndex(nextIndex);
  };
  const goToIndex = (newIndex) => {
    if (animating) return;
    setActiveIndex(newIndex);
  };
  const slides = items.map((item) => {
    return (
      <CarouselItem
        onExiting={() => setAnimating(true)}
        onExited={() => setAnimating(false)}
        key={item.src}
      >
        <img src={item.src} alt={item.altText} />
        <CarouselCaption
        // captionText={item.caption}
        // captionHeader={item.caption}
        />
      </CarouselItem>
    );
  });
  return (
    <Carousel
      activeIndex={activeIndex}
      next={next}
      previous={previous}
      {...args}
    >
      <CarouselIndicators
        items={items}
        activeIndex={activeIndex}
        onClickHandler={goToIndex}
      />
      {slides}
      <CarouselControl
        direction="prev"
        directionText="Previous"
        onClickHandler={previous}
      />
      <CarouselControl
        direction="next"
        directionText="Next"
        onClickHandler={next}
      />
    </Carousel>
  );
}

const inter = Inter({ subsets: ['latin'] })
const items = [
  {
    src: '/assets/img/1.png',
    altText: 'Slide 1',
    caption: 'Slide 1',
    key: 1,
  },
  {
    src: '/assets/img/2.png',
    altText: 'Slide 2',
    caption: 'Slide 2',
    key: 2,
  },
  {
    src: '/assets/img/3.png',
    altText: 'Slide 3',
    caption: 'Slide 3',
    key: 3,
  },
];
export async function getStaticProps() {
  const res = await Axios.get('/api/product')
  //const {data} =  res.json()
  console.log(res)
  return {
    props: {
      data: {}
    }
  }
}
export default function Home({ data }) {
  const gender = ['male', 'female', 'others']
  return (
    <>
      <Head>
        <title>
          E-WASTE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/logo1.PNG" />
      </Head>
      <Scripts src='https://nextjs.org/docs/getting-started/installation' />
      <main>
        <Narvbarhome />
        <Banner />
        <Container fluid className={styles.banner} style={{ marginTop: '-8px' }}>
          <Row className='d-flex justify-content-center py-4 m-2' sm="2"
            xs="1" >

            <Col  >
              <img
                src="/assets/img/banner.jpg"
                width={'90%'}
                height={'90%'}
                alt="Picture of the author"
              />
            </Col>
            <Col>
              <h3 style={{ color: 'purple', marginBottom: '20px' }}>MUA & BÁN E-WASTE </h3>
              <span style={{ color: 'purple', marginBottom: '40px', fontWeight:'800', letterSpacing:'3px',paddingBottom:'20px' }}>NHANH, TIỆN LỢI, GIÁ CAO</span>
              <p style={{ marginBottom: '20px',   fontFamily: 'Florence, cursive', color:'white' }}> Ứng dụng giúp việc mua và bán rác thải điện tử trở nên
                dễ dàng, nhanh chóng, tiện lợi với công nghệ hỗ trợ việc mua bán. </p>
              {/* <a className={styles.buttonTry} href="#">Dùng thử</a> */}
              <Link  className={styles.buttonTry} href="/register">Dùng thử</Link>
            </Col>
          </Row>
        </Container>



        <Container style={{ textAlign: 'center' , paddingTop:'40px',paddingBottom:'40px'}}>
          <h2>Sản Phẩm</h2>
          <div style={{fontFamily: 'Gabarito, cursive'}}>
            <p style={{ marginBottom: '0px' }}>Ứng dụng E-waste là giải pháp phục vụ cho</p>
            <p style={{ marginBottom: '0px' }}>NGƯỜI CẦN BÁN - NGƯỜI CẦN MUA - CHỦ VỰA</p>
            <p>có thể dễ dàng tìm thấy nhau và giao dịch</p>
          </div>
 
          <Row>
            <div className={styles.cardgroup}>
            <div className={styles.cardhome}>
                <Col>
                <Image
                  src="/assets/img/img1.jpg"
                  width={100}
                  height={100}
                  alt="Picture of the author"
                  style={{ textAlign: 'center' }}
                />

                <h6 className={styles.users}> Người cần bán</h6>
                <p className={styles.text}> Đăng thông tin có rác thải điện tử cần bán và tìm kiếm vựa gần nhất.</p>
                <a style={{ color: 'black', textDecoration: 'none', cursor: 'pointer', fontWeight: '800' }} href="#">Tìm hiểu thêm </a>
                </Col>
              </div>
              <div className={styles.cardhome}>
                <Col>
                <Image
                  src="/assets/img/img2.jpg"
                  width={100}
                  height={100}
                  alt="Picture of the author"
                  style={{ textAlign: 'center' }}
                />

                <h6 className={styles.users}>  Người cần mua</h6>
                <p className={styles.text}>  Nhận thông tin của người cần bán và xem giá mua của chủ vựa.</p>
                <a style={{ color: 'black', textDecoration: 'none', cursor: 'pointer', fontWeight: '800' }} href="#">Tìm hiểu thêm </a>
                </Col>
              </div>
              <div className={styles.cardhome}>
                <Col>
                <Image
                  src="/assets/img/img3.jpg"
                  width={100}
                  height={100}
                  alt="Picture of the author"
                  style={{ textAlign: 'center' }}
                />

                <h6 className={styles.users}> Chủ vựa</h6>
                <p className={styles.text}>   Kết nối đến nhiều người thu mua, người bán và cho xem giá thu mua.</p>
                <a style={{ color: 'black', textDecoration: 'none', cursor: 'pointer', fontWeight: '800' }} href="#">Tìm hiểu thêm </a>
                </Col>
              </div>




            </div>
          </Row>


        </Container>


        <Container fluid className={styles.pageinfo}>
          <Row sm="2"
            xs="1">
            <Col>
              <Image
                src="/assets/img/home1_example.png"
                width={400}
                height={270}
                alt="page"
              />
            </Col>
            <Col className={styles.text}>
              <h5>Tham gia với chúng tôi để tiện lợi hóa quá trình mua và bán rác thải điện tử của bạn.  </h5>
              <p>Mua bán thuận tiện, tiết kiệm thời gian ...</p>
            </Col>

          </Row>

        </Container>
        <Footer />
        {/* <Container fluid>
          <Row
            md="4"
            sm="2"
            xs="1"
          >
            <Col className="bg-light border">
              Column
            </Col>
            <Col className="bg-light border">
              Column
            </Col>
            <Col className="bg-light border">
              Column
            </Col>
            <Col className="bg-light border">
              {gender[1]}
            </Col>
          </Row>
        </Container> */}
        {/* body */}

      </main>
    </>
  )
}
export { Banner }
