### POST Create customer
POST http://localhost:8000/api/scrapyard/create
content-type: application/json

{ 
     "address": "76 Tran Huy Lieu",
"name": "vua THu Thuy", 
"image": null,
 "langlat": "500.4, -19.6", 
 "open_time": "thu hai ",
 "user_id":4
    
}

### POST Create customer
Get http://localhost:8000/api/scrapyard/get

content-type: application/json

{ 
     
    
}
### Post Role
POST  http://localhost:8000/api/scrapyard/delete?scrapyard_id=4
content-type: application/json
### POST Create customer

GET  http://localhost:3000/api/myscrapyard
content-type: application/json

